[2025-06-04T01:19:55.565+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-04T01:19:55.610+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:19:53.805047+00:00 [queued]>
[2025-06-04T01:19:55.636+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:19:53.805047+00:00 [queued]>
[2025-06-04T01:19:55.637+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-04T01:19:55.673+0000] {taskinstance.py:2888} INFO - Executing <Task(ExternalTaskSensor): esperar_consumer_dag_S5_ej2_1> on 2025-06-04 01:19:53.805047+00:00
[2025-06-04T01:19:55.700+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'final_dag_ej2_1', 'esperar_consumer_dag_S5_ej2_1', 'manual__2025-06-04T01:19:53.805047+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/Sesion5/Dataset_S5_4_1.py', '--cfg-path', '/tmp/tmpn825acmc']
[2025-06-04T01:19:55.703+0000] {standard_task_runner.py:105} INFO - Job 264: Subtask esperar_consumer_dag_S5_ej2_1
[2025-06-04T01:19:55.706+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8793) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-04T01:19:55.706+0000] {standard_task_runner.py:72} INFO - Started process 8795 to run task
[2025-06-04T01:19:55.731+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-04T01:19:55.811+0000] {task_command.py:467} INFO - Running <TaskInstance: final_dag_ej2_1.esperar_consumer_dag_S5_ej2_1 manual__2025-06-04T01:19:53.805047+00:00 [running]> on host 31d54648d280
[2025-06-04T01:19:56.092+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='final_dag_ej2_1' AIRFLOW_CTX_TASK_ID='esperar_consumer_dag_S5_ej2_1' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T01:19:53.805047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T01:19:53.805047+00:00'
[2025-06-04T01:19:56.094+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-04T01:19:56.143+0000] {baseoperator.py:405} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-06-04T01:19:56.144+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:19:56.146+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2025-06-04T01:20:26.171+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:20:56.194+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:21:26.202+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:21:56.210+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:22:26.217+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:22:56.225+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:23:26.233+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:23:56.240+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:24:26.248+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:24:56.256+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:25:26.263+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:25:56.271+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:26:26.282+0000] {external_task.py:258} INFO - Poking for tasks ['consume_data_dag_S5_ej2_1'] in dag consumer_dag_S5_ej2_1 on 2025-06-04T01:19:53.805047+00:00 ... 
[2025-06-04T01:26:34.297+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-06-04T01:26:34.299+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-06-04T01:26:34.301+0000] {process_utils.py:132} INFO - Sending 15 to group 8795. PIDs of all processes in the group: [8795]
[2025-06-04T01:26:34.302+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 8795
[2025-06-04T01:26:34.302+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-04T01:26:34.309+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-04T01:26:34.313+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=final_dag_ej2_1, task_id=esperar_consumer_dag_S5_ej2_1, run_id=manual__2025-06-04T01:19:53.805047+00:00, execution_date=20250604T011953, start_date=20250604T011955, end_date=20250604T012634
[2025-06-04T01:26:34.321+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-04T01:26:34.354+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=8795, status='terminated', exitcode=2, started='01:19:55') (8795) terminated with exit code 2
