[2025-06-04T02:27:00.779+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-04T02:27:00.792+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_with_variables.run_etl_process manual__2025-06-04T02:26:59.515689+00:00 [queued]>
[2025-06-04T02:27:00.798+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_with_variables.run_etl_process manual__2025-06-04T02:26:59.515689+00:00 [queued]>
[2025-06-04T02:27:00.799+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-06-04T02:27:00.809+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_etl_process> on 2025-06-04 02:26:59.515689+00:00
[2025-06-04T02:27:00.819+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19799) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-04T02:27:00.820+0000] {standard_task_runner.py:72} INFO - Started process 19801 to run task
[2025-06-04T02:27:00.820+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_with_variables', 'run_etl_process', 'manual__2025-06-04T02:26:59.515689+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/Sesion5/DAG_variables.py', '--cfg-path', '/tmp/tmp11fx2jhp']
[2025-06-04T02:27:00.822+0000] {standard_task_runner.py:105} INFO - Job 300: Subtask run_etl_process
[2025-06-04T02:27:00.833+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-04T02:27:00.859+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_with_variables.run_etl_process manual__2025-06-04T02:26:59.515689+00:00 [running]> on host 31d54648d280
[2025-06-04T02:27:00.931+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_with_variables' AIRFLOW_CTX_TASK_ID='run_etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T02:26:59.515689+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T02:26:59.515689+00:00'
[2025-06-04T02:27:00.932+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-04T02:27:00.962+0000] {logging_mixin.py:190} INFO - Error: El archivo /opt/***/dags/Sesion5/data//file_input.csv no existe.
[2025-06-04T02:27:00.962+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-06-04T02:27:00.969+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-04T02:27:00.970+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_with_variables, task_id=run_etl_process, run_id=manual__2025-06-04T02:26:59.515689+00:00, execution_date=20250604T022659, start_date=20250604T022700, end_date=20250604T022700
[2025-06-04T02:27:00.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-04T02:27:01.010+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-04T02:27:01.012+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
